version: '3'
services:
  keycloak:
    container_name: keycloak
    image: summit/keycloak-ip-authenticator:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 9990:9990
      - 8080:8080
